// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PetcoApp.Migrations
{
    [DbContext(typeof(MvcPetsContext))]
    [Migration("20230602220155_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("PetcoApp.Models.Pets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apelido_Animal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dia_chegada")
                        .HasColumnType("TEXT");

                    b.Property<string>("servico")
                        .HasColumnType("TEXT");

                    b.Property<string>("tipo")
                        .HasColumnType("TEXT");

                    b.Property<int>("tipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
